development:
    AWS_ACCESS_KEY_ID: 'AKIAJLF2CJRPYOQL5OOQ'
    AWS_SECRET_ACCESS_KEY: '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'
    S3_BUCKET_NAME: 'osman-gramm'
    AWS_REGION: 'us-east-2'
test:
    AWS_ACCESS_KEY_ID: 'AKIAJLF2CJRPYOQL5OOQ'
    AWS_SECRET_ACCESS_KEY: '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'
    S3_BUCKET_NAME: 'osman-gramm'
    AWS_REGION: 'us-east-2'
production:
    AWS_ACCESS_KEY_ID: 'AKIAJLF2CJRPYOQL5OOQ'
    AWS_SECRET_ACCESS_KEY: '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'
    S3_BUCKET_NAME: 'osman-gramm'
    AWS_REGION: 'us-east-2'
